[package]
name = "Candle Smoke"
description = "Adds a smoke effect to candles."
homepage = "https://www.nexusmods.com/morrowind/mods/55671"
repository = "https://github.com/C3pa/Morrowind-Candle-Smoke"
authors = [ "C3pa" ]
version = "1.1.0"

[dependencies]
assets = [ "Meshes/e/taitech", "Textures/oaab/r0_smoke_01.dds" ]

[tools.mwse]
lua-mod = "Candle Smoke"

[dependencies.mwse]
buildnumber = 3520

[dependencies.mge-xe]
version = ">=0.18.0"
